using new require-friendly mode of lua-nucleo

diff --git a/json2lua b/json2lua
--- a/json2lua
+++ b/json2lua
@@ -1,29 +1,26 @@
 #! /bin/bash
 
-# NOTE: This file uses bash 3.0+ features.
-
-set -e
-set -o errexit
-set -o nounset
-
-LUA="luajit2"
-if [ -z "$(which ${LUA})" ]; then
-  LUA="luajit"
+# Detect Lua interpreter (prefer LuaJIT 2)
+if [ ! -z "${LUA}" ]; then
   if [ -z "$(which ${LUA})" ]; then
-    LUA="lua"
-
-    if [ -z "$(which ${LUA})" ]; then
-      echo "Error: luajit2, luajit or lua executables not found" >&2
-      exit 1
-    fi
+    LUA=""
   fi
 fi
 
-ROOT="${BASH_SOURCE[0]}";
-if([ -h "${ROOT}" ]) then
-  while([ -h "${ROOT}" ]) do ROOT=`readlink "${ROOT}"`; done
+if [ -z "${LUA}" ]; then
+  LUA="luajit2"
+  if [ -z "$(which ${LUA})" ]; then
+    LUA="luajit"
+    if [ -z "$(which ${LUA})" ]; then
+      LUA="lua"
+
+      if [ -z "$(which ${LUA})" ]; then
+        echo "Error: luajit2, luajit and lua executables not found" >&2
+        exit 1
+      fi
+    fi
+  fi
 fi
-ROOT=$(cd `dirname "${ROOT}"` && pwd)
 
 ${LUA} -e "
 
@@ -38,7 +35,7 @@ do
         'try running \'luarocks install luajson\'', '\n'
       )
     io.stdout:flush()
-    io.exit(1)
+    os.exit(1)
   end
 
   json_decode = require('json.decode')
@@ -47,25 +44,22 @@ end
 
 --------------------------------------------------------------------------------
 
-local CODE_ROOT = '${ROOT}'
-if not CODE_ROOT:sub(-1) ~= '/' then
-  CODE_ROOT = CODE_ROOT .. '/'
-end
-
-do
-  -- TODO: This is really hackish!!! Fix it!
-  local res, err = loadfile(CODE_ROOT..'lua-nucleo/strict.lua')
+do -- Bootstrap lua-nucleo
+  local res, err = pcall(require, 'lua-nucleo.module')
   if not res then
     io.stdout:write(
-        err, '\n\n',
-        'did you forget to create lua-nucleo symlink?', '\n'
+        err,
+        '\n\n',
+        'try running \'luarocks install lua-nucleo',
+        ' --from=http://luarocks.org/repositories/rocks-cvs\'',
+        '\n'
       )
     io.stdout:flush()
-    io.exit(1)
+    os.exit(1)
   end
-  res()
+
+  require('lua-nucleo.strict')
 end
-assert(loadfile(CODE_ROOT..'lua-nucleo/import.lua'))(CODE_ROOT)
 
 --------------------------------------------------------------------------------
 
